//! Autogenerated weights for `pallet_ticket`.
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `bench-machine`, CPU: `AMD EPYC 7R13 Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: Some("dev"), DB CACHE: `1024`
//!
//! NOTE: These are placeholder weights. Run `frame-benchmarking` before mainnet.

use frame_support::weights::Weight;

/// Trait for pallet weight functions.
pub trait WeightInfo {
    fn mint() -> Weight;
    fn transfer() -> Weight;
    fn burn() -> Weight;
    fn invalidate() -> Weight;
}

/// Placeholder weights — replace with benchmarked values before mainnet.
pub struct SubstrateWeight<T>(sp_std::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn mint() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn transfer() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn burn() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn invalidate() -> Weight {
        Weight::from_parts(10_000, 0)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

/// No-op weights for use in tests.
impl WeightInfo for () {
    fn mint() -> Weight { Weight::zero() }
    fn transfer() -> Weight { Weight::zero() }
    fn burn() -> Weight { Weight::zero() }
    fn invalidate() -> Weight { Weight::zero() }
}
